# Specifies the schema version Docker Compose should use
version: '3.8'

# 'services' are the individual components (APIs, databases, message brokers) of your system
services:

  # --- 1. INFRASTRUCTURE ---

  # The Redis Cache
  # Container 1: Redis (A simple in-memory key-value store, used for caching)
  redis:
    # Pull the official, ready-to-use Redis image from Docker Hub
    image: redis:latest
    # Ports mapping: "HostPort:ContainerPort"
    # This maps port 6379 on your physical machine to 6379 inside the container.
    # It allows you to use a tool like Redis Insight on your desktop to look inside the cache.
    ports:
      - "6379:6379"

  # --- NEW: The Message Broker ---
  rabbitmq:
    image: rabbitmq:3-management # We use the 'management' tag to get a free Web UI!
    ports:
      - "5672:5672"   # The port our C# code uses to send messages
      - "15672:15672" # The port for the web dashboard (access it at http://localhost:15672)
    # --- NEW: Tell Docker how to check if RabbitMQ is actually ready ---
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    # environment:
    #   - RABBITMQ_DEFAULT_USER=admin
    #   - RABBITMQ_DEFAULT_PASS=admin

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      # 1. The Digital Signature: You legally agreeing to the Developer terms
      - ACCEPT_EULA=Y 
      
      # 2. The License: Unlocking the free Developer edition
      - MSSQL_PID=Developer 
      
      # 3. The Password: Must be strong (Uppercase, lowercase, number, symbol)
      - SA_PASSWORD=SuperSecretPassword123! 
    ports:
      - "1433:1433" # Standard SQL Server port

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin12345 # Set a strong password for the Seq admin user
    ports:
      - "8081:80"   # The Web UI port you will open in your browser
      - "5341:5341" # The internal network port Serilog uses to send the logs
  # --- 2. MICROSERVICES ---


# --- 3. NETWORKING ---
# By default, Docker Compose creates a single network for all services to communicate.
# Each service can refer to others by their service name (e.g., "redis" or "rabbitmq") as the hostname.
