# Specifies the schema version Docker Compose should use
version: '3.8'

# 'services' are the individual components (APIs, databases, message brokers) of your system
services:

  # --- 1. INFRASTRUCTURE ---

  # The Redis Cache
  # Container 1: Redis (A simple in-memory key-value store, used for caching)
  redis:
    # Pull the official, ready-to-use Redis image from Docker Hub
    image: redis:latest
    # Ports mapping: "HostPort:ContainerPort"
    # This maps port 6379 on your physical machine to 6379 inside the container.
    # It allows you to use a tool like Redis Insight on your desktop to look inside the cache.
    ports:
      - "6379:6379"

  # --- NEW: The Message Broker ---
  rabbitmq:
    image: rabbitmq:3-management # We use the 'management' tag to get a free Web UI!
    ports:
      - "5672:5672"   # The port our C# code uses to send messages
      - "15672:15672" # The port for the web dashboard (access it at http://localhost:15672)
    # --- NEW: Tell Docker how to check if RabbitMQ is actually ready ---
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    # environment:
    #   - RABBITMQ_DEFAULT_USER=admin
    #   - RABBITMQ_DEFAULT_PASS=admin

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      # 1. The Digital Signature: You legally agreeing to the Developer terms
      - ACCEPT_EULA=Y 
      
      # 2. The License: Unlocking the free Developer edition
      - MSSQL_PID=Developer 
      
      # 3. The Password: Must be strong (Uppercase, lowercase, number, symbol)
      - SA_PASSWORD=SuperSecretPassword123! 
    ports:
      - "1433:1433" # Standard SQL Server port

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin12345 # Set a strong password for the Seq admin user
    ports:
      - "8081:80"   # The Web UI port you will open in your browser
      - "5341:5341" # The internal network port Serilog uses to send the logs
  # --- 2. MICROSERVICES ---

  api-gateway:
    build: 
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "5050:8080" # The single entry point for the outside world
    depends_on:
      - catalog-api
      - booking-api
  # The Catalog Service (Handles browsing events)
  # Container 2: Catalog.API (Your custom .NET API that serves event data to the frontend)
  catalog-api:
    # Instead of pulling a pre-made image, we tell Compose to build it from our source code
    build: 
      # The 'context' tells Docker where to run the build commands (inside the Catalog.API folder)
      context: ./Catalog.API
      dockerfile: Dockerfile
    # Map localhost:5001 on your browser to the internal container port 8080
    # ports:
    #   - "5001:8080"
    # Inject Environment Variables directly into the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    # Tells Docker: "Do not start this API until the Redis container is up and running"
    depends_on:
      - redis


  # The Booking Service (Handles reserving tickets)
  # Container 3: Booking.API (Your custom .NET API that handles bookings and uses Redis for caching)
  booking-api:
    build: 
      context: ./Booking.API
      dockerfile: Dockerfile
    # Map localhost:5002 on your browser to the internal container port 8080
    # ports:
    #   - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - RABBITMQ_DEFAULT_USER=admin
      # --- THE NETWORKING MAGIC ---
      # In .NET, this overrides 'ConnectionStrings:Redis' in your appsettings.json.
      # Notice the host is exactly "redis", which matches the service name at the top of this file!
      # Docker creates a custom DNS. When your C# code asks for "redis", Docker routes it to the Redis container.
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672
      - SeqUrl=http://seq:5341
      
    depends_on:
      redis:
        condition: service_started # Wait for Redis to start before starting Booking.API
      rabbitmq:
        condition: service_healthy # Wait for RabbitMQ to be healthy before starting Booking.API

  payment-worker:
    build:
      context: ./PaymentProcessor.Worker
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672
      - ConnectionStrings__SqlServer=Server=sql-server;Database=TicketDb;User Id=sa;Password=SuperSecretPassword123!;TrustServerCertificate=True;
    depends_on:
      rabbitmq:
        condition: service_healthy
      sql-server:
        condition: service_started

# --- 3. NETWORKING ---
# By default, Docker Compose creates a single network for all services to communicate.
# Each service can refer to others by their service name (e.g., "redis" or "rabbitmq") as the hostname.
